language: R
sudo: false
cache: packages
warnings_are_errors: true


# unit test on different versions


#  - devel

r_packages:
  - devtools
  - covr

r_github_packages:
  - Dschaykib/newsmd
  - jimhester/lintr


stages:
  - name: unit testing
  - name: coverage and style
  - name: deploy
    if: branch = master


# create code covarage
jobs:
  include:
    - stage: unit testing
      os:
      - linux
      - osx
      r:
      #- oldrel
      - release
    # do not build vignettes...takes too long and times out on travis
      r_build_args: --no-build-vignettes --no-manual
      r_check_args: --no-build-vignettes --no-manual --timings

    - stage: coverage and style
      os: linux
      r: release
      script: Rscript -e 'covr::codecov()'
      script: R CMD INSTALL $PKG_TARBALL
      script: Rscript -e 'lintr::lint_package()'

    - stage: deploy
      script: R CMD INSTALL $PKG_TARBALL
      script: Rscript -e 'if (length(lintr::lint_package()) > 0) stop("There are still lints present")'



notifications:
  email:
    on_success: change
    on_failure: change
