language: R
sudo: false
cache: packages
warnings_are_errors: true


# unit test on different versions
os:
  - linux
  - osx

r:
  - oldrel
  - release

#  - devel

r_packages:
  - devtools
  - covr

r_github_packages:
  - Dschaykib/newsmd
  - jimhester/lintr

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


# create code covarage
jobs:
  include:
    - stage: covarage
      os: linux
      r: release
      script: Rscript -e 'covr::codecov()'
      script: R CMD INSTALL $PKG_TARBALL
      script: Rscript -e 'lintr::lint_package()'


notifications:
  email:
    on_success: change
    on_failure: change
