language: R
#sudo: false
#cache: packages
warnings_are_errors: true


# different versions and OS
os:
  - linux
  - osx
r:
  - oldrel
  - release
  #- devel

# needed packages
r_packages:
  - devtools
  - testthat
  - covr

r_github_packages:
  - Dschaykib/newsmd
  - jimhester/lintr


# unit tests
# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

stages:
  - name: test
  - name: coverage and style (only comments)
    if: branch != master
  - name: coverage and style (as error)
    if: branch = master


# create code covarage
jobs:
  include:
    - stage: coverage and style (only comments)
      os: linux
      r: release
      script:
       - R -e 'covr::codecov()'
       - R -e 'lintr::lint_package()'

    - stage: coverage and style (as error)
      os: linux
      r: release
      script:
       - R -e 'covr::codecov()'
       - R -e 'if (length(lintr::lint_package()) > 0) stop("There are still lints present")'



notifications:
  email:
    recipients:
      - jakob.gepp@statworx.com
    on_success: change
    on_failure: change
