on: [push, pull_request]
name: test-vulnerabilities

jobs:
  test-vulnerabilities:
    runs-on: macOS-latest
    # if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::renv
          extra-packages: any::oysteR

      - name: Check vulnerabilities
        run: |
          audit_renv <- oysteR::audit_renv_lock(dir = dirname(renv::paths$lockfile()))
          testthat::expect_equal(sum(audit_renv$no_of_vulnerabilities), 0)
          ## Tests latest cran versions
          audit_latest <- oysteR::audit(pkg = audit_renv$package, version = rep("*", length(audit_renv$package)), type = "cran")
          testthat::expect_equal(sum(audit_latest$no_of_vulnerabilities), 0)
          ## Tests installed packages
          # there could be differences in the local usage
          audit_install <- oysteR::audit_installed_r_pkgs()
          testthat::expect_equal(sum(audit_install$no_of_vulnerabilities), 0)
        sshell: Rscript {0}
